project:
  type: website

website:
  title: "Bite-sized_workshop"
  navbar:
    left: 
    - text: "R series"
      menu: 
      - text: "Episode 1"
        href: Episode.html
      - text: "Episode 2"
        href: Episode.html
      - text: "Episode 3"
        href: Episode.html
    - text: "Now You See It" 
      href: xxx.html
    - text: "Introduction to QGIS"
      href: introQGIS.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

